source = ./configs/monitors.conf
source = ./configs/programs.conf
source = ./configs/autostart.conf
source = ./configs/env-variables.conf
source = ./configs/look.conf
source = ./configs/input.conf
source = ./configs/key-bindings.conf
source = ./configs/workspaces.conf
source = ./configs/rules.conf

input {
   kb_layout=us,br
   kb_options=grp:win_space_toggle
}