###################
### MY PROGRAMS ###
###################

$terminal = ghostty
$fileManager = nautilus
$menu = rofi -show drun
$chrome = google-chrome-stable
$browser = qutebrowser
$waybar = pkill waybar || waybar
$dbAnalyzer = beekeeper-studio
$requester = /opt/insomnia/insomnia
$musicPlayer = spotify
$discord = vesktop
